version: "3"
services:
  app:
    build:
      context: ../src
      dockerfile: ../Dockerfile
    network_mode: bridge
    image: us.gcr.io/dataplatform-1363/exp-jreport
    tmpfs:
    - /jreport/tmp/pids
