version: "3"
services:
  app:
    build:
      context: ../src
      dockerfile: ../Dockerfile
    network_mode: bridge
    image: asia.gcr.io/gold-stone-241212/exp-jreport
    tmpfs:
    - /jreport/tmp/pids
