reports:
  main:
    file: test.jrxml
    parameters:
      trade_date: report.parameters.trade_date
      report_at: report.parameters.report_at
    data_path: report.records

schema:
  input:
    type: object
    required:
    - report
    properties:
      data:
        type: object
        required:
        - trade_date
        - report_at
        properties:
          trade_date:
            type: string
          report_at:
            type: string